apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: atomica-live-tls
  namespace: default
spec:
  secretName: atomica-live-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: atomica.live
  dnsNames:
    - atomica.live