# kafka-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:3.6.1
          ports:
            - containerPort: 9092
          env:
            # --- Critical Settings ---
            - name: KAFKA_ENABLE_KRAFT
              value: "no"  # Disable KRaft
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"  # Matches the Service name above
            
            # --- Listeners ---
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka-service:9092"  # Matches Kafka Service name
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"

            # --- Optional but Recommended ---
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "true"

---
# kafka-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kafka-service  # <- Backend apps will use this
spec:
  selector:
    app: kafka
  ports:
    - port: 9092
      targetPort: 9092
  type: ClusterIP