name: dockerhub-auth-service

on:
  push:
    branches: [ "master" ]
    paths:
      - server/auth-service/**  # Trigger only when files in auth-service change

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          cd server/auth-service
          docker build -t abinbabu2001/atomica-auth-service .
          docker push abinbabu2001/atomica-auth-service
